pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: 'd0521de2-c7ad-4b55-b399-f12c22447a1f', 
                url: 'https://github.com/phani-snippets/ci-cd-end-to-end',
                branch: 'main'
           }
        }

        // stage('Build Docker'){
        //     steps{
        //         script{
        //             sh '''
        //             echo 'Buid Docker Image'
        //             docker build -t abhishekf5/cicd-e2e:${BUILD_NUMBER} .
        //             '''
        //         }
        //     }
        // }

        stage('Build Docker') {
    script {
        // Change the path to where your Dockerfile actually lives
        sh "docker build -t phani1803/cicd-e2e:1 ./python-jenkins-argocd-k8s/"
    }
}


        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker push phani1803/cicd-e2e:${BUILD_NUMBER}
                    '''
                }
            }
        }
        
        stage('Checkout K8S manifest SCM'){
            steps {
                git credentialsId: 'd0521de2-c7ad-4b55-b399-f12c22447a1f', 
                url: 'https://github.com/phani-snippets/ci-cd-end-to-end',
                branch: 'main'
            }
        }
        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                    withCredentials([usernamePassword(credentialsId: 'd0521de2-c7ad-4b55-b399-f12c22447a1f', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh '''
                        cat deploy.yaml
                        sed -i '' "s/32/${BUILD_NUMBER}/g" deploy.yaml
                        cat deploy.yaml
                        git add deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        git remote -v
                        git push https://github.com/phani-snippets/ci-cd-end-to-end HEAD:main
                        '''                        
                    }
                }
            }
        }
    }
}
