// pipeline {
    
//     agent any 
    
//     environment {
//         IMAGE_TAG = "${BUILD_NUMBER}"
//     }
    
//     stages {
        
//         stage('Checkout'){
//            steps {
//                 git credentialsId: 'd0521de2-c7ad-4b55-b399-f12c22447a1f', 
//                 url: 'https://github.com/phani-snippets/ci-cd-end-to-end',
//                 branch: 'main'
//            }
//         }

//         // stage('Build Docker'){
//         //     steps{
//         //         script{
//         //             sh '''
//         //             echo 'Buid Docker Image'
//         //             docker build -t abhishekf5/cicd-e2e:${BUILD_NUMBER} .
//         //             '''
//         //         }
//         //     }
//         // }

//         stage('Build Docker') {
//     script {
//         // Change the path to where your Dockerfile actually lives
//         sh "docker build -t phani1803/cicd-e2e:1 ./python-jenkins-argocd-k8s/"
//     }
// }


//         stage('Push the artifacts'){
//            steps{
//                 script{
//                     sh '''
//                     echo 'Push to Repo'
//                     docker push phani1803/cicd-e2e:${BUILD_NUMBER}
//                     '''
//                 }
//             }
//         }
        
//         stage('Checkout K8S manifest SCM'){
//             steps {
//                 git credentialsId: 'd0521de2-c7ad-4b55-b399-f12c22447a1f', 
//                 url: 'https://github.com/phani-snippets/ci-cd-end-to-end',
//                 branch: 'main'
//             }
//         }
        
//         stage('Update K8S manifest & push to Repo'){
//             steps {
//                 script{
//                     withCredentials([usernamePassword(credentialsId: 'd0521de2-c7ad-4b55-b399-f12c22447a1f', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
//                         sh '''
//                         cat deploy.yaml
//                         sed -i '' "s/32/${BUILD_NUMBER}/g" deploy.yaml
//                         cat deploy.yaml
//                         git add deploy.yaml
//                         git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
//                         git remote -v
//                         git push https://github.com/phani-snippets/ci-cd-end-to-end HEAD:main
//                         '''                        
//                     }
//                 }
//             }
//         }
//     }
// }







pipeline {
    agent any 
    
    environment {
        DOCKER_USER = "phani1803"
        IMAGE_NAME = "cicd-e2e"
        CREDS_ID = 'd0521de2-c7ad-4b55-b399-f12c22447a1f'
    }
    
    stages {
        stage('Checkout Source') {
           steps {
                git credentialsId: "${CREDS_ID}", 
                url: 'https://github.com/phani-snippets/ci-cd-end-to-end',
                branch: 'main'
           }
        }

        stage('Build Docker') {
            steps {
                // Fixed: Added the 'steps' block required by Jenkins
                echo 'Building Docker Image...'
                sh "docker build -t ${DOCKER_USER}/${IMAGE_NAME}:${BUILD_NUMBER} ./python-jenkins-argocd-k8s/"
            }
        }

        stage('Push to Docker Hub') {
           steps {
                echo 'Pushing to Repo...'
                sh "docker push ${DOCKER_USER}/${IMAGE_NAME}:${BUILD_NUMBER}"
            }
        }
        
        stage('Checkout Manifests') {
            steps {
                dir('manifest-updates') {
                    git credentialsId: "${CREDS_ID}", 
                    url: 'https://github.com/phani-snippets/ci-cd-end-to-end',
                    branch: 'main'
                }
            }
        }
        
        stage('Update & Push Manifest') {
            steps {
                // Entering the subdirectory where deploy.yaml lives
                dir('manifest-updates/python-jenkins-argocd-k8s') {
                    withCredentials([usernamePassword(credentialsId: "${CREDS_ID}", passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh """
                            # Update image tag
                            sed -i "s|image: .*/${IMAGE_NAME}:.*|image: ${DOCKER_USER}/${IMAGE_NAME}:${BUILD_NUMBER}|g" deploy.yaml
                            
                            git config user.email "jenkins@pipeline.com"
                            git config user.name "Jenkins Pipeline"
                            
                            git add deploy.yaml
                            git commit -m "Update image to version ${BUILD_NUMBER} [skip ci]"
                            git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/phani-snippets/ci-cd-end-to-end HEAD:main
                        """                        
                    }
                }
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
    }
}
